services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "7070:80"
    depends_on:
      - app_1
      - app_2
    networks:
      - app_network

  app_1:
    build: app
    expose:
      - "3000"
    networks:
      - app_network

  app_2:
    build: app
    expose:
      - "3000"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge